### ISSUE TITLE
Fix illogical phrase in filters documentation

### ISSUE THREAD

**Issue by fernhub** [api-platform/docs#1008]
I was browsing the documentation of the filters API, but I stumbled upon a phrase that I don't understand, file core/filters.md - right before the link to "**Creating Custom Doctrine MongoDB ODM Filters**", we can see the following sentence:

> When using **ApiFilter** annotation, the declared properties in the services.yaml will not be taken into account. You have to use the **ApiFilter** way (see the documentation).

Perhaps you meant **the ApiResource** annotation instead of the first instance of ApiFilter?

**Comment by dunglas** [comment]
I think that’s good. There is an ApiFilter annotation, and when it is set, it wins over manual service definitions.

**Comment by fernhub** [comment]
Oh yeah you're right, I misread that line! thx
