### ISSUE TITLE
Error in doc "Creating your first API with API Platform" ?

### ISSUE THREAD

**Issue by betd-claumond** [api-platform/docs#103]
Hello,

I'm following the instructions from the doc
https://api-platform.com/doc/1.0/getting-started/api
Creating your first API with API Platform

but I got the an error "[critical] Type "SocialMediaPosting" cannot be found." when executing the generator.

Is there something missing in the doc please ?

I tried with and without the config
rdfa:
    - https://raw.githubusercontent.com/schemaorg/schemaorg/sdo-gozer/data/schema.rdfa
in app/config/schema.yml, but there is almost the same error.

Below both output:
- without the config
$ bin/schema generate-types src/ app/config/schema.yml -vvv
[critical] Type "SocialMediaPosting" cannot be found.
[critical] Type "BlogPosting" cannot be found.
[critical] Type "Article" cannot be found.
[critical] Type "CreativeWork" cannot be found.
[critical] Type "Thing" cannot be found.
[critical] Type "Person" cannot be found.

- with the config
$ bin/schema generate-types src/ app/config/schema.yml -vvv
[critical] Type "SocialMediaPosting" cannot be found.

Plateform: Windows 10 Home
PHP: PHP 5.5.38 (cli) (built: Jul 20 2016 11:16:06) (x86)

Extract from composer.lock
            "name": "api-platform/schema-generator",
            "version": "v1.0.0",

Thanks in advance.

Best regards,
Christophe

**Comment by teohhanhui** [comment]
I'd recommend going with API Platform 2.0

**Comment by betd-claumond** [comment]
Hello,

Thanks for the feedback.

Actually, I was using API Plateform 2.0 initially when following this doc, but I got an error similar to this one. So I tried with the stable version 1.0, but same issue.

Regards,
Christophe

**Comment by dunglas** [comment]
Can you try with changes (especially the `rdfa` property) from this PR? https://github.com/api-platform/docs/pull/89

**Comment by betd-claumond** [comment]
I changed the rfda like this
rdfa:
    - vendor/api-platform/schema-generator/tests/data/schema.rdfa
and got the same issue.

But i guess it's normal with this file, since the file doesn't contain "SocialMediaPosting" in it, isn't it ?
$ grep SocialMediaPosting vendor/api-platform/schema-generator/tests/data/schema.rdfa
> no result

Thanks
Christophe

**Comment by betd-claumond** [comment]
But if I take the whole schema.yml from
https://github.com/api-platform/docs/blob/master/tutorial/api.md
rather than the one from the web
https://api-platform.com/doc/1.0/getting-started/api
it's working !!

I'll go on with this working version so.

Thanks.

Regards,
Christophe
