### ISSUE TITLE
Documentation lack of creating serialization context based on user role

### ISSUE THREAD

**Issue by B0r3d** [api-platform/docs#1044]
Upon browsing the documentation to find answer to my stackoverflow question I realized there documentation lacks how to build the groups based on the current user role I answered the question and I'm pretty sure the documentation could use the answer as a section called "Serialization based on user's role" [here is the question](https://stackoverflow.com/questions/60340261/how-to-set-normalization-groups-based-on-users-role-and-request-method/60346166#60346166) I am pretty sure this can be done more efficiently but I'm still learning the framework I'd appreciate if you made a dedicated section in documentation addressing this issue

**Comment by dunglas** [comment]
Isn’t https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-dynamically what you’re looking for?
