### ISSUE TITLE
Clearly state that phpdocumentor/reflection-docblock needs to be installed

### ISSUE THREAD

**Issue by alexsegura** [api-platform/docs#1048]
Hi,

When using [using Objects As Relations Inside Resources](https://api-platform.com/docs/core/dto/#using-objects-as-relations-inside-resources), if `phpdocumentor/reflection-docbloc` is not installed, it doesn't work. 

This is a little bit tricky, because it may be installed in dev (for example, as a dependency of `phpspec/prophecy`), but not in prod. 

I will submit a pull request for this, it's just to make sure I don't forget about it 🙂

**Comment by dunglas** [comment]
This is only necessary if you document property types using PHPDoc. If you use, for instance, PHP 7.4’s typehints (available only on Symfony 5.1) or Doctrine mappings, it’s not necessary.
Also, when installing API Platform using the official Symfony recipe, or when downloading the official distribution, this package is always added as a dependency.

So why not adding a note about that, but I’m curious to learn how API Platform has been installed to not have it in prod.

**Comment by alexsegura** [comment]
> This is only necessary if you document property types using PHPDoc. If you use, for instance, PHP 7.4’s typehints (available only on Symfony 5.1) or Doctrine mappings, it’s not necessary.

Ok, didn't know 👍 

Actually I had this dependency in my `composer.json` and I didn't understand why.
Removing it in dev didn't break anything, so I removed it. 
But it was needed by API Platform for this, and it worked in dev because it was required by `phpspec/prophecy`. 

And I'm not using latest Symfony structure and Flex, so it doesn't use recipes I think, the packs are not installed. So this explains my problem. 

It people follow standard practices it doesn't happen, so I will close the issue 🙂
