### ISSUE TITLE
[Mercure] Authorization How-To

### ISSUE THREAD

**Issue by darthf1** [api-platform/docs#1050]
Hi,

Reading the docs (and other sources) I cannot find a way to get authorization mode for Mercure working. Hoping to get some feedback here, maybe we can add some of this to the api-platform docs later.

**Read pages:**
https://api-platform.com/docs/core/mercure/#dispatching-private-updates-authorized-mode
https://symfony.com/doc/current/mercure.html#authorization

**Hub config**:
      - ALLOW_ANONYMOUS=0
      - CORS_ALLOWED_ORIGINS=https://localhost
      - DEBUG=1
The hub can be reached by `https://mercure.localhost` and my frontend can be reached by `https://localhost`

**Publisher**
So whenever my entity is updated, an Mercure update is sent because of the `@ApiResource(mercure=true)` annotation. Because I want to only sent the update to specific targets, with the help of the expression language I provide the function which returns the valid Mercure targets.

```php
    /**
      * @ApiResource(
      *     mercure="object.getProject().getMercureTargets()"
      * )
      */
```
My current entity `object` has a relationship with the `Project` entity, which has multiple `owners`. The `getMercureTargets` function returns an array of strings (the string being an allowable target).

```php
    /**
     * @return string[]
     */
    public function getMercureTargets(): array
    {
        return array_map(static function ($owner): string {
            /** @var User $owner */
            return sprintf('/api/users/%s', $owner->getUuid());
        }, $this->getOwners());
    }
```

**Subscriber**
The documentation states that (preferably) cookies should be used when using Authorization. If mercure is enabled, the `Link HTTP header` is added but no `set-cookie` header is added. So I created an `EventSubscriber` class to provide the cookie (from https://symfony.com/doc/current/mercure.html#authorization):

```php
<?php

namespace App\EventSubscriber;

use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Hmac\Sha256;
use Lcobucci\JWT\Signer\Key;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\ResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Core\User\UserInterface;

final class MercureAuthorizationKernelEventSubscriber implements EventSubscriberInterface
{
    /**
     * @var Security
     */
    private $security;

    /**
     * @var string
     */
    private $hubUrl;

    /**
     * @var string
     */
    private $jwtSecret;

    public function __construct(Security $security, string $hubUrl, string $jwtSecret)
    {
        $this->security = $security;
        $this->hubUrl = $hubUrl;
        $this->jwtSecret = $jwtSecret;
    }

    public function onKernelResponse(ResponseEvent $event): void
    {
        if (!$this->security->getUser() instanceof UserInterface) {
            return;
        }

        if (strpos($event->getResponse()->headers->get('link'), 'rel="mercure"') === false) {
            return;
        }

        $username = $this->security->getUser()->getUsername();
        $token = (new Builder())
            ->withClaim('mercure', ['subscribe' => ["/api/users/$username"]])
            ->getToken(new Sha256(), new Key($this->jwtSecret))
        ;

        $event->getResponse()->headers->set(
            'set-cookie',
            sprintf('mercureAuthorization=%s; path=/.well-known/mercure; secure; httponly;', $token)
        );
    }

    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::RESPONSE => ['onKernelResponse', -257],
        ];
    }
}
```
Retrieving the response, I can clearly see that the Cookie is set in the response headers (together with the Mercure link header:
![image](https://user-images.githubusercontent.com/17253332/75162573-0b649d00-571e-11ea-8e27-4f8a7b27e201.png)

So far so good. When connecting with the hub, I use the following code to initiate the EventSource:
```js
new EventSource(url, { withCredentials: true })
```
I would expect the cookie to be sent to the Mercure hub as part of the request, but I cannot see it in the developer console. The response is a `401 Unauthorized`:
![image](https://user-images.githubusercontent.com/17253332/75163234-2d125400-571f-11ea-94da-6a1894363275.png)

*Questions*:
- Is this how Mercure should be configured to enable private updates in combination with API-Platform?
- I would expect that the Cookie would be part of the request and Mercure would return a 200 status code instead of 400. What am I doing wrong here?

**Comment by dunglas** [comment]
- For cookies to work properly, the Hub and your API must share the same domain or subdomain. I‘m not sure browsers consider localhost and mercure.localhost as subdomains. Try something like api.mysite.localhost, mysite.localhost and mercure.mysite.localhost instead
- Your annotation config looks good to me
- API Platform doesn’t set automatically the Mercure cookie (yet), so setting it with a listener is the way to go. You could also set it only one time during the authentication process (when the user logs in) instead of at every response.
- To be shared between subdomains, the “domain” attribute of the cookie must be set to something like “.mysite.localhost” (the initial dot Is only necessary for old browser, but the domain attribute must be present or the cookie will not be shared with subdomains). It’s probably what is missing here.

**Comment by darthf1** [comment]
Thanks you for your feedback! I moved from setting the cookie during a listener to setting it during authentication.

The issue regarding the cookie not setting was because of my `Cors` setup. The cookies are not set when the `Access-Control-Allow-Origin` header value is `*`. When changing the value to my domain the cookie is persisted and passed on subsequent requests.

I also created a custom `JwtProvider` to create a custom `JWT` to only allow specific targets instead of `'*'`.

```php
<?php

namespace App\Mercure;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Lcobucci\JWT\Builder;
use Lcobucci\JWT\Signer\Hmac\Sha256;
use Lcobucci\JWT\Signer\Key;

final class JwtProvider
{
    /**
     * @var EntityManagerInterface
     */
    private $em;

    /**
     * @var string
     */
    private $jwtKey;

    public function __construct(EntityManagerInterface $em, string $jwtKey)
    {
        $this->em = $em;
        $this->jwtKey = $jwtKey;
    }

    public function __invoke(): string
    {
        $targets = array_map(static function ($user): string {
            /** @var User $user */
            return sprintf('/api/users/%s', $user->getUuid());
        }, $this->em->getRepository(User::class)->findAll());

        return (new Builder())
            ->withClaim('mercure', ['publish' => $targets])
            ->getToken(new Sha256(), new Key($this->jwtKey));
    }
}
```

Would this be a good approach? Or should I just keep the default `*` in the JWT?
```json
{
    "mercure": {
        "publish": ["*"]
    }
}
```
