### ISSUE TITLE
roadmap for api-platform?

### ISSUE THREAD

**Issue by waspinator** [api-platform/docs#1056]
I'm trying to find information about the future of api-platform. Is there a roadmap available somewhere?

**Comment by soyuka** [comment]
There isn't much of a roadmap but there are issues to fix and features that are requested on all our api platform projects. See for example: https://github.com/api-platform/core/issues?q=is%3Aopen+is%3Aissue+label%3Abug or https://github.com/api-platform/core/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+%5Brfc%5D.

Please let me know if you have a more precise request, I may help you further.

**Comment by waspinator** [comment]
I guess I just wanted to see if there was a plan for what will be worked on in the future. Particularly when it comes to user accounts. There are many things that API Platform makes incredibly easy, but after watching the "API Platform Part 2: Security" tutorial I'm concerend about how much work is required.

**Comment by soyuka** [comment]
something has been started to improve the user handling part of Api Platform, can't say when it'll be exposed as a new feature.
