### ISSUE TITLE
JWT integration docs is not complete

### ISSUE THREAD

**Issue by maks-rafalko** [api-platform/docs#1058]
There are 2 types of integration with `LexikJWTAuthenticationBundle`

* from the root of `path` (`/`): https://api-platform.com/docs/core/jwt/#configuring-the-symfony-securitybundle
* from the prefix (`/api`): https://api-platform.com/docs/core/jwt/#adding-authentication-to-an-api-which-uses-a-path-prefix

IMO, both of them are incomplete. 

Example: when I use the first type of integration (by default), where all API endpoints start from the `/` root path, I can successfully fetch the `GET /greetings` without any token after JWT integration is done.

There is even a proof [in the tests](https://github.com/api-platform/demo/blob/5ecd2177087afbcce8f88ddfedbc7b95e738d961/api/tests/BooksTest.php#L17) of `api-platform/demo`.

What I would suggest adding is several sentences on how to configure security to **require** a JWT toker for `GET /greetings`

I tried this

```yaml
access_control:
        - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }
```

and it works, but after this, Swagger Documentation is no longer works since it is on `/` path.

*Do you know how to properly configure it*?

The same applies for the second type of integration - when all the endpoints start from `/api` prefix.

I suggest to add something like this to the docs:

```yaml
access_control:
        - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
```

Actually, this is what `LexikJWTAuthenticationBundle` [proposes in its docs](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#configuration).

**Comment by thorau** [comment]
For Swagger Documentation use:
`
access_control:
    - { path: ^/$,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }
`

**Comment by dunglas** [comment]
@chalasr would you mind to take a look? I think you’re the one with the best knowledge of both tools working together :)

**Comment by chalasr** [comment]
See #1063
