### ISSUE TITLE
Broken example for Custom Collection Data Provider

### ISSUE THREAD

**Issue by EmilCataranciuc** [api-platform/docs#1060]
It looks like the documentation at https://api-platform.com/docs/core/data-providers/#custom-collection-data-provider isn't right. If I specify :  \Generator as a return value then react admin throws the following:
Given action "RA/CRUD_GET_LIST_SUCCESS", reducer "total" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.

**Comment by EmilCataranciuc** [comment]
I simply removed : \Generator and it seems to work. Although I am not sure this is right.

**Comment by teohhanhui** [comment]
Not sure how the `\Generator` return type could affect anything. It's the correct return type for a generator function (in which `yield` is used).

**Comment by teohhanhui** [comment]
Okay, the documentation is correct. In your original issue (api-platform/core#3415) you've mentioned that you're returning an empty **array**. You should use the correct return type based on what you're returning from the method. :smile:
