### ISSUE TITLE
ReactAdmin Authentication Support docs are incorrect

### ISSUE THREAD

**Issue by maks-rafalko** [api-platform/docs#1062]
When I'm using JWT, ReactAdmin (generated by defaul) is no longer works.

There is a documentation page - https://api-platform.com/docs/admin/authentication-support/ - that explain how to set up Login page for JWT token.

But the code inside it is completely broken and does not work.

There are many of reasons, let me give you a couple of them:

1. `const fetchHeaders = { Authorization: Bearer ${window.localStorage.getItem("token")} };` - this code immediately resolves to `Bearer null` because on the first run localStorage is empty

2. there are many issues in the console about 401 errors, and even if I correctly implement `authProvider.js` from this article https://marmelab.com/react-admin/Authentication.html - `authProvider.login()` *never executed*. I think the issue is inside `HydraAdmin`, but wasn't able to debug it

**Comment by dunglas** [comment]
Sorry about that, if this part is that broken, I suggest to remove it totally and to just point to the official React Admin docs. With the new version of API Platform Admin, we don’t change anymore the behavior of React Admin, so there is little point to have our own documentation for that anyway. If there is a bug in our bridge with react admin, then we need to fix it.

**Comment by maks-rafalko** [comment]
> With the new version of API Platform Admin, we don’t change anymore the behavior of React Admin

Is it available? Where can I see/try it?

**Comment by maks-rafalko** [comment]
@alanpoulain would you mind writing a conclusion here?

**Comment by alanpoulain** [comment]
The documentation is working. I've made an example in the demo (https://github.com/api-platform/demo/pull/147).

**Comment by maks-rafalko** [comment]
Thank you
