### ISSUE TITLE
Permission denied issue with generated keys for JWT on Docker for Linux

### ISSUE THREAD

**Issue by maks-rafalko** [api-platform/docs#1067]
There is [a snippet with the code in documentation](https://api-platform.com/docs/core/jwt/#installing-lexikjwtauthenticationbundle) that explains how to generate `private.pem`/`public.pem` files during installation of JWT auth.

Also, there is an example in `api-platform/demo` with exactly the same code:

https://github.com/api-platform/demo/blob/5ecd2177087afbcce8f88ddfedbc7b95e738d961/api/docker/php/docker-entrypoint.sh#L18-L22

However, this approach, when these files are generated in `docker-entrypoint.sh`

* works fine on MacOS
* partially works on Linux, until we want to rebuild the image

#### What is the difference?

`Docker for Mac` and Docker on Linux work differently in regard to user permissions.

When you are on MacOS, generated files are owned by the user of host (MacOS) machine, while when you are on Linux, generated files are owned by `root` user - default user in the Alpine docker image.

And when you want to rebuild the image, after `private.pem`/`public.pem` are generated, you get the following error **on Linux**:

```bash
docker-compose build php
```

```bash
PermissionError: [Errno 13] Permission denied: '/path/to/api-platform/config/jwt/private.pem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 282, in build
  File "compose/project.py", line 373, in build
  File "compose/service.py", line 1027, in build
  File "site-packages/docker/api/build.py", line 154, in build
  File "site-packages/docker/utils/build.py", line 31, in tar
  File "site-packages/docker/utils/build.py", line 183, in 
```

#### Why does it happen?

Because `Dockerfile` in `api-platform/platform` distribution contains the following line:

https://github.com/api-platform/api-platform/blob/ca2835cdb319a60179ab5b06325dcb4084a8c22f/api/Dockerfile#L99

```
COPY config config/
```

and host's user does not have permission to copy `config/jwt`.

**Comment by soyuka** [comment]
Docker permissions are always a mess and there is no clean solution. Do you have a possible solution in mind?

**Comment by maks-rafalko** [comment]
Not really, I'm using MacOS and didn't experience this issue until my colleagues on Linux pointed out to it.

One of them fixed it by changing a group

```bash
chgrp -R docker api/config/jwt
```

Another colleague fixed it by `chmod`ing to 777.

None of these solutions sounds like a perfect way for me.

Probably @teohhanhui can help here who is more familiar with Docker (as far as I see :) )?

**Comment by maks-rafalko** [comment]
Highly recommend for reading this artice https://jtreminio.com/blog/running-docker-containers-as-current-host-user/

It fully covers this issue with many details.

**Comment by maks-rafalko** [comment]
Found a simple solution, opened a doc PR: https://github.com/api-platform/docs/pull/1068

Tested locally, works as expected
