### ISSUE TITLE
How to use "defaults" attribute of the operations in @ApiResource

### ISSUE THREAD

**Issue by krstns** [api-platform/docs#1091]
I think I went through all of the docs but I was unable to find any info regarding the `defaults~ attribute used as an example in here: https://api-platform.com/docs/core/operations/#configuring-operations

Where can I find more info about it? Could this be used with `@ApiFilter` annotation? If so, how could this be used with the `ExistFilter`?

**Comment by soyuka** [comment]
defaults configures the route default options in symfony, I'm not sure to understand your use case.
