### ISSUE TITLE
Overide order of embed relation in item operation

### ISSUE THREAD

**Issue by atomatis** [api-platform/docs#1114]
Hi,

I have some entity with [embed relations](https://api-platform.com/docs/core/serialization/#embedding-relations).
I can use 
`@ApiResource(attributes={"order"={"my_entity.my_embed_relation": "ASC"}})`
for [overide sorting](https://api-platform.com/docs/core/default-order/) in collection operation, but it's dosen't work with item operation.

I understand that the logic behind it is that usually, we don't need to sort a single item.

Is it because I am doing it wrong or this functionality could be missing?

**Comment by soyuka** [comment]
item operations can't be sorted indeed. You should add a custom filter to do so.
