### ISSUE TITLE
Dynamically added groups for (de)normalization

### ISSUE THREAD

**Issue by benjaminrau** [api-platform/docs#112]
Hi there.

This is just a question, not a bug report.

Can you tell me where in the following example the admin_input group is added only for Books, or isnt this the case?

For my understanding with the code from this example the group admin_input is added on each ApiResource when conditions match.

https://github.com/dunglas/doc/blob/new_getting_started/core/serialization-groups-and-relations.md#changing-the-serialization-context-dynamically

Thanks for your help.

Cheers Ben

**Comment by dunglas** [comment]
Indeed, in this example, the `admin_input` group is always added in the context (for any resource class).

Maybe can it be nice to add another exemple where the new group is added only for a given entity using a `is_a()` call in a guard clause.

@benjaminrau do you think you can update the doc to cover this use case?

**Comment by benjaminrau** [comment]
About my proposed change on docs: 
In my project the subject was sometimes a proxy object. So i wasnt able to do ```$subject instanceof Book``` but rather ```ClassUtils::getRealClass(get_class($subject)) === Book:class```

I dont know if that is common case, if so, i should add this to docs.

**Comment by dunglas** [comment]
Yes it's a common pitfall. However even with proxies, `instanceof` should work.

**Comment by benjaminrau** [comment]
Closing this because the question was answered by dunglas and ive added it to docs.
