### ISSUE TITLE
Document OAuth2 Flow Grant Type configuration values

### ISSUE THREAD

**Issue by abzolv** [api-platform/docs#1127]
Currently the Swagger UI JS uses non-standard values for the allowed OAuth2 flow grant types (`accessCode`, `authorizationCode`, `clientCredentials`, etc.), instead of the OAuth2 standards of `authorization_code`, `client_credentials`, etc.

Please document the fact that the grant names must be Camel Cased in the `api_platform.yaml` config file, or change the Symfony Bridge so that it will automatically camel case the `oauth.flow` value read in from the `api_platform.yaml` config file.

**Comment by soyuka** [comment]
these are documented in https://github.com/api-platform/docs/blob/2.5/core/configuration.md. Note that some improvements have been done recently in https://github.com/api-platform/core/pull/3407 to help with openapi standard.
