### ISSUE TITLE
Operation route prefix in YAML format

### ISSUE THREAD

**Issue by SherinBloemendaal** [api-platform/docs#1137]
Hi,

I am trying to set a operation route prefix inside my YAML configuration but i cant get it working.
When i click on the YAML button, i do not see any routePrefix attribute.
https://api-platform.com/docs/core/operations/#prefixing-all-routes-of-all-operations

I tried this:
```
resources:
  App\Entity\Book:
    attributes:
      routePrefix: /v1
      ...
    collectionOperations:
      ...
```
And
```
resources:
  App\Entity\Book:
    routePrefix: /v1
    attributes:
      ...
    collectionOperations:
      ...
```
And this
```
resources:
  App\Entity\Book:
    properties:
      routePrefix: /v1
      ...
    collectionOperations:
      ...
```

Thanks

**Comment by soyuka** [comment]
routePrefix doesn't exist AFAIK. In the documentation example we're using a symfony Route to declare the operation so that we can handle the path.
