### ISSUE TITLE
Dynamic validation groups service in YAML

### ISSUE THREAD

**Issue by Kenariosz** [api-platform/docs#1141]
Hey!

I'm little bit confused. I'd like to use the dynamic validation group service with yaml config. So i followed [the documentation](https://api-platform.com/docs/core/validation/#dynamic-validation-groups).
First i tried the annotation setup and it worked. Then i moved back the annotation config to yaml and it didn't work.

Here is the original code which i used
```
Validator service

<?php
declare(strict_types=1);

namespace App\Validator;

final class GroupsGenerator
{
    public function __invoke(Order $order)
    {
        return ['Default', 'specGroup'];
    }
}
```
```
yaml config snippet

attributes:
        validation_groups: [App\Validator\GroupsGenerator]
```

Then i tried to add different methods to the service:
```
<?php
declare(strict_types=1);

namespace App\Validator;

final class GroupsGenerator
{
    public function group1(Order $order)
    {
        return ['Default', 'group'];
    }
    public static function group2(Order $order)
    {
        return ['Default', 'group'];
    }

    public function __invoke(Order $order)
    {
        return ['Default', 'createSalesOrder'];
    }
```
I used the following yaml configs
```
    attributes:
        validation_groups: [App\Validator\GroupsGenerator, 'group1']
```
```
    attributes:
        validation_groups: [App\Validator\GroupsGenerator, 'group2']
```
Both are worked.

So my question: which is the proper way to setup this service via yaml?

**Comment by alanpoulain** [comment]
`ValidationGroupsGeneratorInterface` is registered for autoconfiguration as `public`, it should not be an issue.
