### ISSUE TITLE
Documentation publication date is wrong

### ISSUE THREAD

**Issue by walva** [api-platform/docs#1182]
Hello,

I was looking on who to integrate Behat with a API Platform project and I notice the date of the documentation is incorrect like below.

"31 juil. 1985"

![image](https://user-images.githubusercontent.com/3897363/95994057-1b0d2f00-0e30-11eb-94f3-0364d424cd81.png)

It's definitely minor but worth a fix IMO.

Best regards.

**Comment by dunglas** [comment]
Good catch indeed.

**Comment by soyuka** [comment]
We looked into this and the publicationDate actually comes from our tests and is not related to the documentation ?!
