### ISSUE TITLE
Create a full User management feature

### ISSUE THREAD

**Issue by ClementVincent** [api-platform/docs#1220]
Hi !

I've been trying to create my User Management feature for several days and I found a lack of information in the documentation and on the web (especially on the good practices).

I acheived to do it by "cheating" a bit and I'm not sure it's the best way to do. Anyway, I've already started to write something for my own usage but I would be glad if we could discuss on the good pratices and maybe add something in the doc (as it's a usual feature to have and it's always good to have examples on how to customize API-Platform default behavior.) :)

Thank you in advance !

**Comment by soyuka** [comment]
This is more related to Symfony and if you follow https://symfony.com/doc/current/security.html you'll be able to do everything you want. Often https://github.com/lexik/LexikJWTAuthenticationBundle is used or even https://github.com/thephpleague/oauth2-server-bundle
