### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Gu3** [api-platform/docs#1230]
Hi ! 
There is a dead link here : https://api-platform.com/docs/core/serialization/#name-conversion

![image](https://user-images.githubusercontent.com/5227741/101325283-caccaf00-386b-11eb-8c37-1e4427f4529e.png)

Cheers !

**Comment by alanpoulain** [comment]
Hello, thanks for reporting, could you make a PR to change it?

**Comment by Gu3** [comment]
No problem, but I think It's already done !
