### ISSUE TITLE
[GraphQL] How to disable stages in yaml ?

### ISSUE THREAD

**Issue by JulienSellier** [api-platform/docs#1241]
Hello there,

I want to disable some stages in my GraphQL API but I can't figure out how to achieve that in yaml ?

The GraphQL documentation is not talking about yaml configuration:
https://api-platform.com/docs/master/core/graphql/#disabling-resolver-stages

Can you help me please ? :)

**Comment by alanpoulain** [comment]
Duplicates https://github.com/api-platform/docs/issues/1025.
