### ISSUE TITLE
typo in exemple

### ISSUE THREAD

**Issue by paulywebster** [api-platform/docs#132]
In the getting started "Creating your First API with API Platform, in 5 Minutes" there is a typo in the example using POST on the REVIEW resource :

There is a comma at the end of the last row who thrown an error.

This code 
```javascript
{
    "book": "/books/1",
    "rating": 5,
    "body": "Interesting book!",
    "author": "Kévin",
    "publicationDate": "September 21, 2016",
}
```
should be
```javascript
{
    "book": "/books/1",
    "rating": 5,
    "body": "Interesting book!",
    "author": "Kévin",
    "publicationDate": "September 21, 2016"
}
```

**Comment by dunglas** [comment]
Thanks for the report @paulywebster!

Fixed by 4865510658fefe66ef45bd0bbc1818c052a00878.
