### ISSUE TITLE
Add documentation on "how to hack api-plateform packages"

### ISSUE THREAD

**Issue by florent-andre** [api-platform/docs#1354]
Hi there ! 
What do you think of expand the "contributing guidelines" with something more "concrete" that explain how-to install api-plateform related packages in order to fix/pr/hack ? 
I feel myself a little bit only on that, and achieve something like under.
Do you think it could be a good addition ? If yes, how do you see this ? (added to contributing.md or a specific file or...).

Widely open to suggestions & improvements, here a possible content for this doc :

# Contributing to an api-plateform package 

* Note : 
Commands on this documentation are based on a personnal api-plateform template project named `api-pf-project`.  
In this project you want to fix something on the `schema-generator`, but you only have it as a dependency.  
Let's do some configs to push a PR ! 

Following scripts here are based on `schema-generator` package. Change commands to the package you want to hack ! 

* 1/ set up local copy of the package
```
cd api-pf-project/api
mkdir libs
cd libs
git clone git@github.com:api-platform/schema-generator.git
```

* 2/ modify `composer.json` to use your local copy of the package
  * 2.1/ add local repo infos : 
  ```
  "repositories": [{
        "type": "path",
        "url": "./libs/schema-generator",
        "options": {
            "symlink": true
        }
    }]
  ```
  * 1.2/ change require package version to @dev :
  ``` 
  "api-platform/schema-generator": "@dev",
  ```

* 3/ install the package's dependencies
```
docker-compose exec php sh -c 'cd libs/schema-generator ; composer install'
or (when supported)
docker-compose exec -w libs/schema-generator php composer install
``` 

* 4/ update main project dependencies : 
```
docker-compose exec php composer update
```

* 5/ Run the tests : 
```
# php unit
docker-compose exec php sh -c 'cd libs/schema-generator ; vendor/bin/simple-phpunit'

# phpstan
docker-compose exec php sh -c 'cd libs/schema-generator ; vendor/bin/phpstan analyse'

# e2e (@TODO : is it functional ?)
docker-compose exec php sh -c 'cd libs/schema-generator ; php bin/compile'

# coding style (@TODO : missing dependencies to fix)
docker-compose exec php sh -c 'cd libs/schema-generator ; php-cs-fixer fix --dry-run --format=checkstyle | cs2pr'
```

* 6/ Enjoy & hack ! 
You can now run this command with your local copy : 
```
docker-compose exec php vendor/bin/schema generate src/ config/schema.yaml
```
* 7/ Restaure to official package
  * 7.1/ remove changes in composer.json
  * 7.2/ run : `docker-compose exec php composer update`
  * 7.3/ remove local copy in `libs/`

* sources : 
  * https://medium.com/developer-space/preparing-a-comfortable-development-environment-to-develop-a-new-symfony-bundle-417f4d8248be

**Comment by dunglas** [comment]
Alternatively you can remove the vendors then run `composer update --prefer-source` and hack in the vendors directly. I prefer this method as it's easier.

**Comment by florent-andre** [comment]
Neat !! 
This one liner is cool ! 
But may be less explicit when working in team. 
Do I drop this / theses options somewhere in doc or do i close this issue ? 
Have great day !

**Comment by alanpoulain** [comment]
It can already be found here: https://github.com/api-platform/core/blob/main/CONTRIBUTING.md.
