### ISSUE TITLE
Missing part in operations page

### ISSUE THREAD

**Issue by Vinorcola** [api-platform/docs#1355]
Hello there,

By reading the doc page on operations (https://api-platform.com/docs/core/operations/#prefixing-all-routes-of-all-operations), I find out that there is a piece missing, that may probably have been dropped by mistake.

Indeed, part **Prefixing all routes of all operations** is showing the good PHP exemple, but YAML and XML examples are incorrect or mixed with a missing part that should be **Creating Custom Operations and Controllers**. And just above that code example block, we have the following text:

```
API Platform will automatically map this post_publication operation to the route book_post_publication. Let's create a custom action and its related route using annotations:
```

This text introduce an operation unpresented before (except in YAML example above) and is talking about a custom operation while we are in the **Prefixing all routes of all operations** part of the doc.

Taking the history of the doc page on Github, I can find back a more complete doc here : https://github.com/api-platform/docs/blob/0439ec17b79b87f33582c6290a0c43ed60b3e90c/core/operations.md#creating-custom-operations-and-controllers

So I think an entire subset of the page have been dropped by mistake at some point, and the code example linked to prefixing all routes have been messed up.

**Comment by alanpoulain** [comment]
Thanks for reporting it.
Here is the PR: https://github.com/api-platform/docs/pull/1439.
The documentation was not removed, you can find it here: https://api-platform.com/docs/core/controllers/#creating-custom-operations-and-controllers
