### ISSUE TITLE
Update Blackfire installation

### ISSUE THREAD

**Issue by lobodol** [api-platform/docs#1368]
Hello there,

I followed [this doc](https://api-platform.com/docs/core/performance/#profiling-with-blackfireio) to install Blackfire. Everything worked fine except it warns me about deprecation of the agent:

"The v1 is deprecated and will sunset on Sept, 1st 2021. Consider upgrading to v2 soon".

Regards,

**Comment by lobodol** [comment]
Moreover, I suggest adding config in `docker-compose.override.yml` instead of `docker-compose.yml`.

What do you think about it?

**Comment by alanpoulain** [comment]
Yes it would be better in `docker-compose.override.yml`.
