### ISSUE TITLE
Update link to fixtures bundle

### ISSUE THREAD

**Issue by lobodol** [api-platform/docs#1434]
Hello there,

The repository https://github.com/hautelook/AliceBundle suddenly disappeared and is no longer reachable.

https://twitter.com/tfidry/status/1436090358950150145  
https://stackoverflow.com/questions/69126582/hautelook-alicebundle-is-gone-whats-going-on-what-now/69129097#69129097

As mentioned [here](https://github.com/nelmio/alice/issues/1089#issuecomment-916664460), a temporary solution is to use this fork: https://github.com/theofidry/AliceBundle

When things will get stable, I think API-Platform documentation ([the fixtures part](https://api-platform.com/docs/distribution/testing/#creating-data-fixtures)) should be updated.

Regards!

**Comment by alanpoulain** [comment]
Done here: https://github.com/api-platform/docs/commit/6551753cd5e53d60e4646e11083d7f61d3813d3b
