### ISSUE TITLE
Add syntax highlight for code blocks

### ISSUE THREAD

**Issue by welcoMattic** [api-platform/docs#1547]
Code will be more comfortable to read with syntax highlighting (like https://github.com/shikijs/shiki, or https://prismjs.com/)

**Comment by alanpoulain** [comment]
It's already the case, isn't it?
![image](https://user-images.githubusercontent.com/10920253/168114320-ad2aeea8-99dc-45df-9d78-582d998e3d0c.png)

**Comment by welcoMattic** [comment]
Not here (Firefox 100) 
<img width="729" alt="apip" src="https://user-images.githubusercontent.com/773875/168122067-d5b4ab3f-05ac-4b57-ac65-8e8290490322.png">

**Comment by welcoMattic** [comment]
My bad, after clearing the cache my previous screenshot becomes false :smile:
