### ISSUE TITLE
Use ProviderInterface as DTO for collection operation

### ISSUE THREAD

**Issue by RomainNeoweb** [api-platform/docs#1615]
Hi,

Just updated to 3.1 and I have an issue using the ProviderInterface as an Output DTO for collection operation (as it's written in the documentation there : https://api-platform.com/docs/main/core/dto/ & https://api-platform.com/docs/main/core/state-providers/ .
I cannot figure out how I can access the data to transform it into my DTO as I was able to do with the DataTransformerInterface.

**Comment by rsereir** [comment]
Same issue for me.
I think you can do a foreach on ProviderInterface with your transformation but i don't really know how you can keep ApiPlatform Filters

https://github.com/api-platform/core/issues/5023

**Comment by RomainNeoweb** [comment]
A colleague of mine found the solution, you can use the normalizer https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-on-a-per-item-basis .
Works with ItemOperation and CollecionOperation.
ping @rsereir
