### ISSUE TITLE
Wrong Yaml example on 2.7 doc ?

### ISSUE THREAD

**Issue by partulaj** [api-platform/docs#1707]
Hello,

I'm using api-platform 2.7 and I notice that Yaml example on the 2.7 branch of the documentation don't work for me and are the same as the 3.x branch. Did I miss something or does this commit d74cd614b1fe18a8e1126e5847ee795387649e18 shouldn't be on the 2.7 branch of the doc ?

**Comment by alanpoulain** [comment]
The 2.7 documentation considers that you have migrated your resources to the new metadata system: https://api-platform.com/docs/core/upgrade-guide/.
You probably are using the old one.
