### ISSUE TITLE
Nested lists doesn't render well

### ISSUE THREAD

**Issue by jeremyVignelles** [api-platform/docs#1760]
On page https://api-platform.com/docs/create-client/typescript/ , at the bottom of the page, the files are actually generated at the level below "interfaces". However, in the documentation, the rendered HTML shows it at the same level:

![image](https://github.com/api-platform/docs/assets/3399355/94ed16a6-7cf0-4a8c-b514-b49a7ad79954)

However, the source markup seems correct:

https://github.com/api-platform/docs/blob/df883f361a9365557bd1fb5555e15601df6ad12b/create-client/typescript.md?plain=1#L30-L35

I assume that's an issue with the markdown generator, but I didn't dig too deep to see what's going on.

**Comment by vinceAmstoutz** [comment]
Issue solved as you can see
![image](https://github.com/user-attachments/assets/30a1bec1-0db4-4f8c-89ae-aef087ab844a)
