### ISSUE TITLE
PR merged on 3.0 isn't on 3.1+

### ISSUE THREAD

**Issue by vasilvestre** [api-platform/docs#1765]
Hey, a merged PR on 3.0 isn't on 3.1+. See here the version 3.0 : https://api-platform.com/docs/v3.0/distribution/testing/

It contains Foundry and the recent version does not.

PR : https://github.com/api-platform/docs/pull/1699

**Comment by alanpoulain** [comment]
Please wait for the merge of `3.0` to `3.1`.

**Comment by soyuka** [comment]
https://github.com/api-platform/docs/pull/1767/ done :)
