### ISSUE TITLE
How to disable globaly one operation ? 

### ISSUE THREAD

**Issue by cedriclombardot** [api-platform/docs#1773]
Found 

item_operations: ~
collection_operations: ~

option : https://api-platform.com/docs/core/configuration/  but not in the code !

**Comment by vinceAmstoutz** [comment]
https://api-platform.com/docs/core/configuration/ references the configuration reference with its default values.  

```yaml
item_operations : ~
collection_operations : ~
```

describes that api_platform uses the default operations (they are described in the table in the introduction to https://api-platform.com/docs/core/operations/).
