### ISSUE TITLE
Missing version select in documentation

### ISSUE THREAD

**Issue by MrVapeur** [api-platform/docs#1774]
Hello, 
Since the overall UI of the documentation has been renewed, I can't find any version select in order to read the documentation of a past/unmaitained version of the framework. 
The URL keeps working well (https://api-platform.com/docs/v2.5/core/ for exemple).
is it possible to put it back?
Thanks in advance !

**Comment by alexislefebvre** [comment]
You have to scroll at the bottom of the menu:

> ![image](https://github.com/api-platform/docs/assets/2071331/0106f493-2c5b-4cc2-8e4d-5ab2e8def4e6)

**Comment by vinceAmstoutz** [comment]
Works perfectly now for all versions
![image](https://github.com/user-attachments/assets/a5eef148-e07f-40af-aa5f-95a7694e8b56)
