### ISSUE TITLE
Anchored links on the same page are redirecting to the root "/docs/core"

### ISSUE THREAD

**Issue by franckranaivo** [api-platform/docs#1777]
Am I the only one or somehow every anchor links which reference the same page but different section inside the page keeps redirecting to the root page.

Typically, [here](https://api-platform.com/docs/core/upgrade-guide/#i39m-migrating-from-26-and-want-to-prepare-for-30) if you want to see instructions in *api:upgrade-resource command* it just keeps redirecting to the root page (https://api-platform.com/docs/core/).

The link on the markdown version of the page seems right, maybe some redirection configuration is missing ?

**Comment by soyuka** [comment]
is this fixed?

**Comment by franckranaivo** [comment]
Yes, I think so. As documentation have changed from the time of creation of this issue, this one is not relevant anymore. I tested some internal links, but all seems to be okay.
If I see similar issues, I will open a new one. But for now I close this.
Thanks @soyuka
