### ISSUE TITLE
ContextAwareDenormalizerInterface is deprecated, but used in docs

### ISSUE THREAD

**Issue by asdfMaciej** [api-platform/docs#1801]
The usage can be found under https://api-platform.com/docs/core/serialization/#plain-identifiers

**Comment by pieterocp** [comment]
Having checked, looks like it's only in the older versions, 2.7, 3.0, 3.1 and 3.2. Later versions aren't using this any more, so if someone is using newer versions of the docs, they should get examples without this deprecation.
