### ISSUE TITLE
Document Platform.sh deployment

### ISSUE THREAD

**Issue by KDederichs** [api-platform/docs#1833]
Hey,

I was wondering if you guys happen to have some basic docs about how to deploy Api-Platform on Platform.sh.

As much as I love all the custom stuff you're adding to it (Mercure, Frankenphp) it becomes incredibly confusing to try to figure out how to deploy an Api-Platform project there with all those features (I honestly didn't even manage to tell if it's possible or not).

So I was wondering if you could add some documentations related to Platform.sh deployments and if there's limits and such.

**Comment by flovntp** [comment]
Hi, i miss this one, does this blogpost help? 
https://platform.sh/blog/how-to-host-multiple-applications/

**Comment by vinceAmstoutz** [comment]
Check our [Deployment documentation](https://api-platform.com/docs/deployment/) which includes a paragraph at the end about PaaS (including Platform.sh).

Also, you're welcome to contribute, check our [CONTRIBUTING.md](https://github.com/api-platform/docs/blob/4.0/CONTRIBUTING.md) and submit your suggestions.

Thanks!
