### ISSUE TITLE
Wrong schema.org link in "Handling Relations" document

### ISSUE THREAD

**Issue by mttsch** [api-platform/docs#1838]
Affected site: https://api-platform.com/docs/admin/handling-relations/

https://github.com/api-platform/docs/blob/4ecf9aed55d9451ff62d2558efe2c3ed91b3bbb7/admin/handling-relations.md?plain=1#L5

The link in this line links to https://api-platform.com/docs/admin/handling-relations/schema.org instead of https://api-platform.com/docs/admin/schema.org.

**Comment by vinceAmstoutz** [comment]
Issue solved,  as you can see now on https://api-platform.com/docs/admin/handling-relations/
