### ISSUE TITLE
Many (or all ?) internal links from the "distribution" page are broken and leads to a 404 page.

### ISSUE THREAD

**Issue by Morgan-Capron** [api-platform/docs#1840]
The links on the "distribution" page pointing to the API documentation seems to all lead to a 404 error page.

They works in the Github preview.

Examples:
- [a PHP library (Core)](https://api-platform.com/core/index)
- [Docker](https://api-platform.com/deployment/docker-compose)
- [You can also help us improve the documentation of this page.](https://github.com/api-platform/docs/edit/distribution.md)

404: https://api-platform.com/deployment/index/
200: https://api-platform.com/docs/deployment/

Note: without ending slash "/" this example redirect to an error page
https://api-platform.com/docs/deployment -> https://api-platform.com/docs/deployment/distribution

Error:
NoSuchKeyThe specified key does not exist.No such object: api-platform-website-v3/deployment/distribution/index.html

**Comment by vinceAmstoutz** [comment]
We are no longer concerned (issues solved)
