### ISSUE TITLE
The GraphQL examples require the Greeting entity, but the tutorial asked us earlier to remove it.

### ISSUE THREAD

**Issue by Morgan-Capron** [api-platform/docs#1841]
In the tutorial "[Getting Started With API Platform: Create Your API and Your Jamstack Site](https://api-platform.com/docs/distribution/)", we been asked to "delete the file api/src/Entity/Greeting.php.". 

But in the "Adding GraphQL Support" chapter, the examples require the Greeting file.

**Comment by vinceAmstoutz** [comment]
If you need it after, you can recreate it using the demo.
