### ISSUE TITLE
Add Anchor Links to improve documentation sharing

### ISSUE THREAD

**Issue by Ninhache** [api-platform/docs#1846]
Hi,

While reviewing documentation, I sometimes find the need to share it with others. I've realized that this isn't really possible with your documentation, which I see as a problem.

Specifically, I'm referring to the anchor links present in some documentations, similar to those in the [NextJS](https://nextjs.org/docs/app/building-your-application/optimizing/scripts#strategy) and [VueJS](https://vuejs.org/guide/essentials/forms.html#select) documentation.

I believe the addition of anchor links to your documentation could significantly enhance the ease of sharing specific sections, as I mentioned earlier.

Thank you for considering my request

**Comment by vinceAmstoutz** [comment]
Anchor Links are available, an example

https://api-platform.com/docs/core/extending/#system-providers-and-processors

And the Anchor also appears for the link to be copied:

![image](https://github.com/user-attachments/assets/7555cb20-8da7-469f-a5b4-9da0b8f7dc32)
