### ISSUE TITLE
It seems there is currently a lint issue with https://github.com/api-platform/docs/blob/3.2/core/upgrade-guide.md

### ISSUE THREAD

**Issue by Angatar** [api-platform/docs#1850]
It seems there is currently a lint issue with https://github.com/api-platform/docs/blob/3.2/core/upgrade-guide.md
which is not impacted at all by my pull request (#1848) but this still broke the checks:

Line 30 and Line 50 of  the /core/upgrade-guide.md have both an additional trailing space that generate an error during lint check. Do I need to integrate the fix of this file in my PR as well?
Last commit involved in this issue on /core/upgrade-guide.md by @soyuka

_Originally posted by @Angatar in https://github.com/api-platform/docs/issues/1848#issuecomment-1840505899_

**Comment by soyuka** [comment]
let's avoid the duplicate I'll fix this shortly we always take a look at the CI to see if the problem comes from the PR or not :)
