### ISSUE TITLE
What is [codeSelector] ? Is it or bug or else ?

### ISSUE THREAD

**Issue by pounard** [api-platform/docs#1851]
We can see it all over the place, such as:

![image](https://github.com/api-platform/docs/assets/341855/6ae35027-98f1-40f8-a29d-1c8c4744b8e9)

Always the same form:

```
[codeSelector]

... some code samples ...

[/codeSelector]
```

It's either broken, or there's something I do not understand.

Right now, the screencap comes from https://api-platform.com/docs/v3.2/core/security/ I saw many others in various pages.

Thank you for everything!

**Comment by soyuka** [comment]
yes it's a bug I need to fix :)

**Comment by vinceAmstoutz** [comment]
The problem is fixed, there are no more occurrences in the code base, we now use `<code-selector>` .
