### ISSUE TITLE
Missed Subresource yaml configurations

### ISSUE THREAD

**Issue by alebedev80** [api-platform/docs#1858]
How to declare subresource by YAML configuration?

```
    uriVariables: [
        'companyId' => new Link(fromClass: Company::class, toProperty: 'company'),
        'id' => new Link(fromClass: Employee::class),
    ],
```

YAML examples completely missed [here](https://api-platform.com/docs/core/subresources/)
P.S. current documentation quality much worse when i choose API platform (was version 2.4) :(

**Comment by vinceAmstoutz** [comment]
Solved in docs if you are using version `>= 3.1` on  https://api-platform.com/docs/core/subresources/ with the YAML code selector, for example: 
![image](https://github.com/user-attachments/assets/a976c17a-1589-4586-b6e2-aec1b385926c)
