### ISSUE TITLE
Absolute internal links are broken

### ISSUE THREAD

**Issue by lhapaipai** [api-platform/docs#1884]
I and thank you for your awesome doc !

It seems there is an issue with your absolute internal links when they are converted from markdown to html, **we have lost the `href` attribute**.

## Reproduction

go to page : https://api-platform.com/docs/core/errors/
Section "Exception status code decision" 
click : "Error Provider"

your are always in the same place : https://api-platform.com/docs/core/errors/

**expected** : you are redirected to : https://api-platform.com/docs/guides/error-provider/

## Issue

the markdown content
```md
There are many ways of configuring the exception status code we recommend reading the 
guides on how to use an [Error Provider](/guides/error-provider) or create an
 [Error Resource](/docs/guides/error-resource).
```
is rendered
```html
<p>There are many ways of configuring the exception status 
code we recommend reading the guides on how to use an 
<a href>Error Provider</a> or create an <a href>Error 
Resource</a>.
```

**Comment by alexislefebvre** [comment]
See also #1780
