### ISSUE TITLE
Subresources formatting error

### ISSUE THREAD

**Issue by Adz10kvtech** [api-platform/docs#1904]
https://api-platform.com/docs/core/subresources/

Just below the paragraph 

"Now to create a new way of retrieving an Answer we will declare another resource on the Answer class. To make things work, API Platform needs information about how to retrieve the Answer belonging to the Question, this is done by configuring the uriVariables:"

The formatting for the php example is wrong.

<img width="1135" alt="image" src="https://github.com/api-platform/docs/assets/53915382/13b256eb-3bf4-4d42-8113-7b9383850324">

Cheers

**Comment by xalopp** [comment]
I noticed that there are several identical PR addressing this issue: #1912 #1885 #1881 #1878  #1877 #1875

Merging one of these PRs would solve this issue.

**Comment by soyuka** [comment]
thanks!
