### ISSUE TITLE
Contribute to documentation

### ISSUE THREAD

**Issue by sblum51** [api-platform/docs#1935]
Hi,
I found a typo (url issue) in documentation. I don't find how to suggest an update with a PR , is it possible ?

**Comment by dunglas** [comment]
Yes. Just open a PR on https://github.com/api-platform/docs

**Comment by vinceAmstoutz** [comment]
@sblum51 As mentioned in #2029, I’ve opened a PR to add detailed documentation aimed at helping future contributors.
