### ISSUE TITLE
Broken link grom Getting Started to Admin

### ISSUE THREAD

**Issue by fzaninotto** [api-platform/docs#1962]
The link to API Platform Admin in the [Distribution Getting Started tutorial](https://api-platform.com/docs/distribution/) is broken: 

<img width="1217" alt="image" src="https://github.com/user-attachments/assets/8e284f45-1093-4fbd-85b2-37c77d3ae2f4">

Clicking on the link moves the page up but doesn't change the content. 

Source: https://github.com/api-platform/docs/blob/main/distribution/index.md#L739

I'm not sure how to fix it.

**Comment by vinceAmstoutz** [comment]
Thanks for reporting the bug @fzaninotto. It's now working again
