### ISSUE TITLE
Simplifying our Release Phases Request - Rest API and Webhooks public docs

### ISSUE THREAD

**Issue by spaltrowitz** [api-platform/docs#2025]
As part of our work to [Simplify our Release Phases](https://github.com/github/product/discussions/1665), there are a lot of internal and process documents to be updated. One of them is the REST API docs, and I have confirmed with @hypercycle that this is the repo to raise the request. We are expecting all internal teams to update public-facing guidance by **October 18th** for a unified effort ahead of Universe.

Based on the announcement above, the main changes that will need to be made are:
- **Alpha** and **Beta** (private beta, public beta) mentions need to change to **Preview** (private beta -> private preview, public beta -> public preview)
- **Deprecation** -> **Closing Down**
- **Sunset** -> **Retired**

I met with @jc-clark from the docs team, who clarified that this team would own the following portions of public facing docs for REST API and Webhooks, and we would need your assistance to:

- Update any of the terminology mentions above. For example, **Deprecation notice** -> **Closing Down Notice** https://github.com/search?q=repo%3Agithub%2Fgithub%20%22Deprecation%20notice%22&type=code
- Update all relevant api endpoints that include this terminology https://api-platform-docs.githubapp.com/rest-api/find-by-route?query=deprecated---update-a-custom-role
- Programmatically check future PRs for use of old terminology. @jc-clark mentioned he could potentially see a PR [like this](https://github.com/github/github/pull/344002/files) falling through the cracks when people use words like deprecated as part of the PR body. With no automated checks in place, it would be really hard to catch all instances. (This could be implemented post-October 18th)

Please let me know if you need any clarification on this request.

Thanks,
Shari

**Comment by dunglas** [comment]
Hi @spaltrowitz, I think you opened this issue on the wrong organization.
