### ISSUE TITLE
Examples for CSV and YML missing on the Content Negotiation page

### ISSUE THREAD

**Issue by blaues0cke** [api-platform/docs#206]
I am tryin to output a complex response as CSV like [the documentation](https://api-platform.com/docs/core/content-negotiation) says. I just figured out that at least the following is missing in the docs, but I am not sure if I am 100% correct about the content types. So would be nice if someone could confirm this. I will create pull request then.

```
    formats:
        csv:      ['text/csv']
        yaml:     ['text/yaml']
```

Also, should I add my custom normalizer when its done? Out of the box its not possible to just enable the `csv` format:

![image](https://cloud.githubusercontent.com/assets/5159398/25810503/990c1180-3410-11e7-8b83-5548acc92064.png)

```
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "To use the CSV encoder, each line in the data array must have the same structure. You may want to use a custom normalizer class to normalize the data format before passing it to the CSV encoder."
}
```

Todo:

- [x] Figure out the best way to fix this issue (here is an example: https://github.com/api-platform/core/issues/316)
- [x] Update the documentation (seems someone tried this before: https://github.com/api-platform/docs/pull/21)

**Comment by soyuka** [comment]
I managed to add `text/csv` but if the entity is complex (relations for example) it's hard to do a generic output. So, by using a custom normalizer you can prepare a simple array for it to be correctly serialized.

**Comment by dunglas** [comment]
Hi,

You need Symfony 3.2+ to use the CSV or the YAML encoder. The error is not related and is self explanatory, to expose CSV you need to be sure that each lines has the exact same structure (looks at collections for instance).

Regarding YAML, there is no official MIME type registered yet for this format. I suggest to use `text/x-yaml`.

**Comment by blaues0cke** [comment]
@dunglas Thank you! I am using Symfony 3.2.3, and the encoder works until a 1:N relation occurs.

A resource with no sub-relations serialized works:
![image](https://cloud.githubusercontent.com/assets/5159398/25837736/7a342aa2-348f-11e7-8a1a-8e0e887053b4.png)

But a entity with N relations that are serialized does not work:
![image](https://cloud.githubusercontent.com/assets/5159398/25837762/99383a6a-348f-11e7-82c4-ac9ff7cd48dd.png)

Here as JSON to understand the format:
![image](https://cloud.githubusercontent.com/assets/5159398/25837779/acdb60c4-348f-11e7-9f1d-2599cd3faea5.png)

I dont think that is a bug, so my apporoach would be to define a serialitation group especially for cvs-"exporting" that just hides all 1:n-relations. Is that a way you would recommend to fix this issue?

**Comment by soyuka** [comment]
How do you put your N relations in the same linear table? I think it's the root cause of this and why one may need a custom normalizer.

**Comment by blaues0cke** [comment]
@soyuka I think this error is caused by "products". In my case one "campaign" has 1-N products. This is ok for `JSON` but of course not for `CSV`.

**Comment by soyuka** [comment]
I don't get how is the normalizer supposed to format a table inside a table (read collection inside a collection) into one single table? I think that the csv serializer will work fine if you have a simple collection of items.

**Comment by blaues0cke** [comment]
Yes, but in this case my collection is very complex. I will try to use a custom group or a custom normalizer to "hide" that complex relations in the case of the csv format:

![image](https://cloud.githubusercontent.com/assets/5159398/25838473/95bbeefa-3493-11e7-8994-7a2795a74e11.png)

**Comment by soyuka** [comment]
Yeah I totally understood your issue here.

Could you write this as a table by hand? I would have a hard time doing so, but this would be easy to do if the data was something like this:

```json
[
    {
        "productTitle": "foo",
        "productImage": "bar",
        "brand": "bonduelle"
    }...
]
```

**Comment by blaues0cke** [comment]
So, I added a custom item normalizer as explained (for v1) here: https://github.com/api-platform/core/issues/316 that just removes "sub arrays" from the response (since I don't need them in my case):

```
    api.serializer.normalizer.item:
        public: false
        class: AppBundle\Serializer\CustomItemNormalizer
        arguments: [ '@api_platform.serializer.normalizer.item' ]
        tags: [ { name: serializer.normalizer } ]
```

```
<?php

namespace AppBundle\Serializer;

use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

/**
 * Class CustomItemNormalizer
 * @package AppBundle\Serializer
 */
class CustomItemNormalizer implements NormalizerInterface, DenormalizerInterface
{
    /**
     * @var NormalizerInterface
     */
    private $normalizer;

    /**
     * CustomItemNormalizer constructor.
     *
     * @param $normalizer
     */
    public function __construct(NormalizerInterface $normalizer)
    {
        if (!$normalizer instanceof DenormalizerInterface) {
            throw new \InvalidArgumentException('The normalizer must implement the DenormalizerInterface');
        }

        $this->normalizer = $normalizer;
    }

    /**
     * {@inheritdoc}
     */
    public function denormalize($data, $class, $format = null, array $context = array())
    {
        return $this->normalizer->denormalize($data, $class, $format, $context);
    }

    /**
     * {@inheritdoc}
     */
    public function supportsDenormalization($data, $type, $format = null)
    {
        return $this->normalizer->supportsDenormalization($data, $type, $format);
    }

    /**
     * {@inheritdoc}
     */
    public function normalize($object, $format = null, array $context = array())
    {
        $result = $this->normalizer->normalize($object, $format, $context);

        if (strtolower($format) == 'csv') {
            if (is_array($result)) {
                foreach ($result as $key => $value) {
                    if (is_array($value)) {
                        if (array_keys(array_keys($value)) === array_keys($value)) {
                            unset($result[$key]);
                        }
                    }
                }
            }
        }

        return $result;
    }

    /**
     * {@inheritdoc}
     */
    public function supportsNormalization($data, $format = null)
    {
        return $this->normalizer->supportsNormalization($data, $format);
    }
}
```

This makes the csv finally work even for complex entities. Will now start to create a pr for the docs.

**Comment by blaues0cke** [comment]
Done, further feedback in the pr: https://github.com/api-platform/docs/pull/210
