### ISSUE TITLE
Add an XML / YML example for "Serialization Groups and Relations"

### ISSUE THREAD

**Issue by dkarlovi** [api-platform/docs#207]
[Docs](https://api-platform.com/docs/core/serialization-groups-and-relations) says "The Symfony Serializer component allows to specify the definition of serialization using XML, YAML, or annotations. "

But there's no sample how to setup for example this:

    /**
     * @ApiResource(
     *     attributes={"normalization_context"={"groups"={"get"}}},
     *     itemOperations={
     *          "get"={"method"="GET"},
     *          "put"={"method"="PUT", "normalization_context"={"groups"={"put"}}}
     *     }
     * )
     */

in XML or YAML. AFAIK there's also no XML Schema provided ([as Symfony does](http://symfony.com/doc/current/components/serializer.html#attributes-groups)) so it's ever harder to discover the functionality.

It would be great to provide a sample XML / YAML config, even just in a Git repo somewhere. I've looked in core's tests, there isn't one there either.

**Comment by soyuka** [comment]
You can find examples here: https://github.com/api-platform/core/tree/master/tests/Fixtures/FileConfigurations

We should have added those to the documentation, for example with [custom operations](https://github.com/api-platform/docs/blob/master/core/operations.md) we added yaml and xml configuration examples.

Is this what you were looking for? We have a schema for XML metadata [here](https://github.com/api-platform/core/blob/master/src/Metadata/schema/metadata.xsd).

**Comment by dkarlovi** [comment]
That was exactly what I was looking for, but I looked for those in `tests/Fixtures/TestBundle/Resources/config`. :( So it's just a matter of discoverability. That's the same reason I've assumed you don't ship XML schema: [there's none in the docs](https://api-platform.com/docs/core/getting-started#mapping-the-entities).

Having those in the docs would surely help, yes.

Thank you very much @soyuka, closing this.

**Comment by soyuka** [comment]
@dkarlovi I'll leave this open until someone has the time to update the docs regarding this issue! Thanks for the report.

**Comment by Simperfit** [comment]
It is now documented

**Comment by egorzot** [comment]
Here is the [example](https://api-platform.com/docs/core/serialization#using-serialization-groups) in docs

**Comment by dunglas** [comment]
It's a goal for the project to document available configuration options in all formats.
But it's tedious and it takes time.
Help on this topic would be very welcome.

It can be contributing the missing configs, or improving the website to display a format selector like on the Symfony website.
