### ISSUE TITLE
id property not in docs.jsonld#Entity

### ISSUE THREAD

**Issue by VaN-dev** [api-platform/docs#213]
Hello,

I have a entity Invoice with a primary key "id"
If I browse the docs.jsonld#Invoice, I dont find any reference to this property. So on my client, my hydra parser based on API doc cannot understand how to hydrate this property and set it to null.

Do I need to configure something for api-platform to expose this primary key in the jsonld doc of an entity ?

**Comment by dunglas** [comment]
I think that it's a bug, the `id` property is explicitly excluded from the Hydra doc but shouldn't. It's a legacy of when we was excluding automatically the `id` property. This behavior has been removed, but the Hydra generator hasn't been updated accordingly.

**Comment by Simperfit** [comment]
@VaN-dev feel free to reopen this if you still needs something to be documented, or please create an issue in https://github.com/api-platform/core directly.
