### ISSUE TITLE
Misleading docs for master branch

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/docs#23]
For example, api-bundle/the-event-system.md still talks about the no longer existent custom events...

I remember @dunglas updating some docs last time to mention that they're outdated, but those notices seem to be gone now. Is this a glitch when extracting the docs from DunglasApiBundle, or is it intended?

**Comment by dunglas** [comment]
No it's not intended. The doc will need a major upgrade for 2.0 (when the code will be done).

**Comment by Simperfit** [comment]
Was looking into the the event systems, is there something that replace it directly ?
ping @dunglas

**Comment by teohhanhui** [comment]
@Simperfit You can use the Symfony events (e.g. `kernel.view`) directly.
