### ISSUE TITLE
How do you build the docs?

### ISSUE THREAD

**Issue by mickaelandrieu** [api-platform/docs#279]
Hello,
there are some rendering errors in docs but I can't check my fixes will work if I can't reproduce the rendering :(

Do you use mkdocs for instance?

Mickaël

**Comment by dunglas** [comment]
Hi, the process is described here: https://github.com/api-platform/website

But we are working on a brand new website, and the process will change soon. It will be 100% automated.

**Comment by soyuka** [comment]
I think it's done with https://github.com/api-platform/website but I don't have more informations :p.

**Comment by Simperfit** [comment]
We are pushing in the docs:gh-pages and it deploys it, AFAIK.

Closing this, feel free to reopen if you need more information ;).

**Comment by mickaelandrieu** [comment]
@Simperfit yes, but how do you deploy docs on your local machine to check the rendering ?
