### ISSUE TITLE
Bad support of "middle click" on https://api-platform.com/docs/

### ISSUE THREAD

**Issue by laurentj** [api-platform/docs#287]
By clicking with the middle button of our mouse, on an internal link, we expect that it respects the behavior of our browser (in my case, with Firefox, it should open the link into a new tab). But it doesn't. It opens the content into the same tab. It's very annoying (and not consistent with external links).

(and why having 1.65 MB of JS to just display few KB of html ? Static HTML content is enough for documentation IMHO...)

**Comment by soyuka** [comment]
Can you give link examples? I tried a couple but links opened in a new tab :).

**Comment by dunglas** [comment]
We're working on a new website, so I don't think it is worth it to try to fix the old one.

**Comment by laurentj** [comment]
@soyuka any internal links. For example: https://api-platform.com/docs/core/events , then click on "Creating custom operations and controllers" (link to https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers) : it is opened in the same tab with Firefox.

Notice that there is not the bug with Google Chrome.

**Comment by Simperfit** [comment]
Since the new website has been pushed, this seems to be resolved.
