### ISSUE TITLE
Changing the Serialization Context Dynamically example is wrong

### ISSUE THREAD

**Issue by norkunas** [api-platform/docs#298]
```php
public function createFromRequest(Request $request, bool $normalization, array $extractedAttributes = null) : array
{
    $context = $this->decorated->createFromRequest($request, $normalization, $extractedAttributes);
    $subject = $request->attributes->get('data');

    if ($subject instanceof Book && isset($context['groups']) && $this->authorizationChecker->isGranted('ROLE_ADMIN') && false === $normalization) {
        $context['groups'][] = 'admin_input';
    }

    return $context;
}
```

I've tried to decorate context builder but the `$subject` is always null.

**Comment by klb-rodriguez** [comment]
Hello @norkunas , I have the same problem too.

Have you solved the problem?

**Comment by norkunas** [comment]
Hey @klb-rodriguez, currently i'm just checking if `$extractedAttributes['resource_class']` is the needed instance.

**Comment by klb-rodriguez** [comment]
Hello @norkunas, I have checked the code, and I have no problem now, the method createFromRequest is called twice, the first time the variable data is null, the second time it has all data, I don't know why the method is called twice. My mistake was I have a exit() method and I only was seeing the first time execution.

**Comment by norkunas** [comment]
I've encountered this problem only on denormalization, for normalization `$subject` is not null..
