### ISSUE TITLE
Rename project / repository

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/docs#39]
It should be changed to an intuitive form, e.g. `symfony/symfony-docs`

So perhaps `api-platform/docs`

**Comment by theofidry** [comment]
:+1: for `api-platform/docs`

**Comment by teohhanhui** [comment]
ping @api-platform/core-team

**Comment by sroze** [comment]
I don't see the interest as `doc` is good enough to me tbh

**Comment by teohhanhui** [comment]
@soyuka - from https://github.com/api-platform/doc/issues/66#issue-161147236

> Could the repository be renamed to api-platform-docs, like symfony does it?
>
> It's better when forking, doc is too common.

**Comment by soyuka** [comment]
Btw this is the same for `api-platform/core`, when forking it becomes `user/core` and when you want to override composer repository without too much tweaks, you have to keep the same repo name.

**Comment by dunglas** [comment]
Why not, but we'll loose consistency with `wore`. Laravel use `docs` for instance: https://github.com/laravel/docs

**Comment by teohhanhui** [comment]
@soyuka:

> when you want to override composer repository without too much tweaks, you have to keep the same repo name

Not true. Composer only cares about the name in `composer.json`.

**Comment by soyuka** [comment]
I read this:

> Also note that the override will not work if you change the name property in your forked repository's composer.json file as this needs to match the original for the override to work.

https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

But indeed, it's the `composer.json` name that should match not the repository, thanks!

Nevermind then, feel free to close this ;).

**Comment by teohhanhui** [comment]
I'm still interested in renaming `doc` (an alien form) to `docs` (the familiar form).

**Comment by theofidry** [comment]
>I'm still interested in renaming doc (an alien form) to docs (the familiar form).

I wouldn't go as far as saying alien, as it's fairly common: [145,928 results for `doc`](https://github.com/search?p=1&q=doc&type=Repositories&utf8=%E2%9C%93) vs. [27 730 for `docs`](https://github.com/search?utf8=%E2%9C%93&q=docs&type=Repositories&ref=searchresults).

However I do prefer `docs` so I'm still 👍 for it :)

**Comment by teohhanhui** [comment]
@theofidry The search for `doc` matches `docs`, `Docker` among others. :smile:

**Comment by theofidry** [comment]
ha fair point, doesn't change that's it's widly used still. But it's more a matter of preference I guess as both are valid.

**Comment by soyuka** [comment]
+1 for `docs` too
