### ISSUE TITLE
Translation of api-platform documentation into spanish language

### ISSUE THREAD

**Issue by siersod-utopian** [api-platform/docs#393]
Greetings api-platform Team!

I would like to help translating the documentation of api-platform into spanish language. In order to do so, I have a couple of questions.

Should I make a new branch called Spanish and do the translation from there? an i18n/es-ES folder? or how would it be more convenient to have this translation?

Thanks in advance for your answer.

**Comment by alanpoulain** [comment]
I think it will be too hard to maintain, so I'm :-1: for this.

**Comment by dunglas** [comment]
Sorry for the time taken to answer you. I agree with @alanpoulain, it will be very difficult to maintain them.

However, translating at least the getting started guide would make sense. Another option would be to create community repositories with translations, marked as non-official.
