### ISSUE TITLE
Serialization menu item not found

### ISSUE THREAD

**Issue by soyuka** [api-platform/docs#398]
Menu has serialization-groups-and-relations but the documentation is available under serialization

Did we forgot to update the menu/index according to recent changes?

ref https://github.com/api-platform/api-platform/issues/567

**Comment by soyuka** [comment]
I'm so :+1: to the scripting stuff, what tech for the scripting? (php/js/bash)

**Comment by dunglas** [comment]
I'd say JS has we already have https://github.com/api-platform/website/blob/master/bin/generate-nav

**Comment by soyuka** [comment]
2min code we could work with:

```
yarn add glob markdown-toc
```

```javascript
const fs = require('fs')
const toc = require('markdown-toc')
const glob = require('glob')

// This is the path to the "docs" repository root
const sections = glob.sync('./*')

sections.forEach((section) => {
  const stat = fs.statSync(section)
  const index = `${section}/index.md`

  if (!stat.isDirectory() || !fs.existsSync(index)) {
    return
  }

  console.log(section)
  doTocFile(index)
  const files = glob.sync(`${section}/*.md`)
  files.forEach((file) => {
    doTocFile(file)
  })
})

function doTocFile (file) {
  const root = toc(fs.readFileSync(file, 'utf8')) //e.content (title), e.slug (slug), e.i (number in page), e.lvl (indent)

  console.log(root.json.map((e) => `${e.i} - ${e.content}`))
}
```

**Comment by dunglas** [comment]
Maybe can we just hardcode the order in the script (a map order => file name, and append unknown files at the end)? ping @ginifizz @mauchede

**Comment by dunglas** [comment]
We may also use a markdown comment: https://stackoverflow.com/a/20885980/1352334

`[//]: # order:1`

**Comment by alanpoulain** [comment]
Has been resolved.
