### ISSUE TITLE
Dynamic validation groups in YAML

### ISSUE THREAD

**Issue by ahonymous** [api-platform/docs#416]
Hi. I use YAML configuration format on the project.
@dunglas , could you add example for using a static method  of same entity in YAML in this doc https://api-platform.com/docs/core/validation/#dynamic-validation-groups  ?

    resources:
       AppBundle\Entity\Book:
           ...
           attributes:
               validation_groups: Book::validationGroups

**Comment by jkgroupe** [comment]
Hi, you should try with this syntax

```
resources:
   AppBundle\Entity\Book:
       ...
       attributes:
           validation_groups: [App\Entity\Book, 'validationGroups']
```

**Comment by jescalere** [comment]
Hi, you should try with this syntax

```
resources:
   AppBundle\Entity\Book:
       ...
       attributes:
           validation_groups: [App\Entity\Book, 'validationGroups']
```
