### ISSUE TITLE
Overwrite swagger templates

### ISSUE THREAD

**Issue by cduran433** [api-platform/docs#432]
I want to remove the logo on the top right of the documentation. 

Reading [documentation](https://api-platform.com/docs/core/swagger) I can find how to overwrite Swagger information, but I am trying to find some way to overwrite Swagger templates, and I don't know how to do it.

Is it possible to do it?

**Comment by dunglas** [comment]
Yes.
The template is here: https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig

You can override it as described in this docs: https://symfony.com/doc/current/templating/overriding.html

It would be nice to add mention about this in the Swagger documentation page. Would you mind opening a PR to add this?

**Comment by cduran433** [comment]
Thank you.
I am not able to override the template. I create in my api platform this route with a new template:

- templates/bundles/BridgeSymfonyBundle/SwaggerUi/index.html.twig but the template i not overrided.

Regarding the PR, It is the first time that I am going to create a PR. Any further information that I should know? I am going to follow the github steps.

**Comment by dunglas** [comment]
Can you try with `templates/bundles/ApiPlatformBundle/SwaggerUi/index.html.twig`?

**Comment by cduran433** [comment]
It works! Thank you, I am going to do the PR.
