### ISSUE TITLE
Remove “Handling Relations to Collections”?

### ISSUE THREAD

**Issue by alexislefebvre** [api-platform/docs#483]
On the page https://api-platform.com/docs/admin/handling-relations-to-collections, it is written:

> Currently, API Platform Admin doesn't handle `to-many` relations. The core library [is being patched](https://github.com/api-platform/core/pull/1189) to document relations to collections through OWL.
> 
> Meanwhile, it is possible to manually configure API Platform to handle relations to collections.

But https://github.com/api-platform/core/pull/1189 was merged on 29 Jun 2017.

So it looks like this page is documenting a configuration that is not necessary anymore? Should the page be rewritten or removed entirely?

**Comment by dunglas** [comment]
Yes we must remove it!

**Comment by alexislefebvre** [comment]
Just to be sure, are the code in the *Let's customize the components* and *We'll make one last improvement to our admin* parts still relevant? Are they useful to customize the display, or is it already done automatically?
