### ISSUE TITLE
Refactor code on “Managing Files and Images”?

### ISSUE THREAD

**Issue by alexislefebvre** [api-platform/docs#485]
The code block in https://api-platform.com/docs/admin/getting-started#managing-files-and-images contains 5 levels of indentation (I counted numbers of `return`).

I find it difficult to read and understand.

I think that it should be written by using several functions (or another way) and adding comments to explain how it works.

**Comment by alexislefebvre** [comment]
On this page, `RichTextField` is imported but never used.

**Comment by darkiron** [comment]
I can not implement upload function in admin. No errors. Filed was not renderer with fileInput. Juste textInput
