### ISSUE TITLE
Document proper usage of toMany collections (denormalization + validation)

### ISSUE THREAD

**Issue by soyuka** [api-platform/docs#504]
See https://github.com/api-platform/core/pull/1534 

@bendavies what's the validation trick? Put the validation on the property instead of the getter?

**Comment by bendavies** [comment]
replace
```xml
<property name="invoices">
    <constraint name="Valid"/>
</property>
```
with
```xml
<getter property="invoices">
    <constraint name="Valid"/>
</getter>
```

**Comment by soyuka** [comment]
https://github.com/api-platform/docs/pull/740 finally took time to document that :D
