### ISSUE TITLE
Filters.md RegExpFilter  not working with 2.2.8

### ISSUE THREAD

**Issue by Selion05** [api-platform/docs#513]
Using `AbstractContextAwareFilter` instead of  `AbstractFilter`
 
and adding 
```
        // otherwise filter is applied to order and page as well
        if (
            !$this->isPropertyEnabled($property, $resourceClass) ||
            !$this->isPropertyMapped($property, $resourceClass)
        ) {
            return;
        }
```
in `filterProperty()` seems to work

**Comment by teohhanhui** [comment]
Can you send a PR targeting the `2.2` branch? :smile:

**Comment by Selion05** [comment]
sure #514 
for next time should I just start with a PR?

**Comment by teohhanhui** [comment]
For small fixes, yes. For larger changes, you might want to discuss it with us first so that you don't waste your effort. :smile:
