### ISSUE TITLE
Update the doc according to the changes.

### ISSUE THREAD

**Issue by Simperfit** [api-platform/docs#55]
- [x] Should not be `@Resource` but `@ApiResource`
- [x] Should not be `@Property` but `@ApiProperty`
  see #56 
- [x] Update the docs about serialization groups by @dunglas 
- [x] Update the FOSUserBundle docs by @dunglas 
- [ ] Update the angularJS tutorial / add a to-go angular backend.
- [ ] maybe do something about react
- [x] Update docs about nelmio & swagger.
- [ ] add to doc https://github.com/api-platform/core/issues/521
- [x] add range filters to the doc
- [x] add doc about HAL

Do you see other things ?

**Comment by dunglas** [comment]
[ ] Update the AngularJS tutorial

**Comment by soyuka** [comment]
@dunglas no updates on my end on the angularjs tutorial, what did you have in mind?

**Comment by dunglas** [comment]
I've tweaked a bit the API response in the server side tutorial. The client part must be updated accordingly.

**Comment by fxkopp** [comment]
- [ ] Fix the Gherkin Link at https://github.com/api-platform/docs/blob/master/tutorial/api.md#specifying-and-testing-the-api

**Comment by shaisachs** [comment]
I believe the composer installations need to be updated. At https://github.com/api-platform/docs/blob/master/distribution/index.md:

`php bin/console ...`

Should be

`php app/console ...`

**Comment by teohhanhui** [comment]
@shaisachs Please upgrade to v2.

@Simperfit Can this be closed?

**Comment by dunglas** [comment]
@shaisachs btw, Composer will only download v2 if you use PHP 7+.

**Comment by Simperfit** [comment]
Yes we can close this.

**Comment by shaisachs** [comment]
Aaaah I see - I was using php 5.6. Thanks!
