### ISSUE TITLE
Add a `how to create dev/debug stage using xdebug` section

### ISSUE THREAD

**Issue by hschaeidt** [api-platform/docs#551]
see https://github.com/api-platform/api-platform/pull/782

**Comment by Larzack** [comment]
I added this on my php.ini file ( doc included )

# Xdebug
# https://blog.philipphauer.de/debug-php-docker-container-idea-phpstorm/
xdebug.remote_autostart=1
xdebug.remote_mode=req
xdebug.remote_handler=dbgp
xdebug.remote_connect_back=1
xdebug.remote_port=9000
xdebug.remote_enable=1
xdebug.remote_host=gateway.docker.internal
xdebug.idekey=PHPSTORM
xdebug.remote_log="/tmp/xdebug.log"
## For MAC/Docker
#https://www.lionware.solutions/2017/10/19/setting-up-xdebug-docker-phpstorm/
#https://serversforhackers.com/c/getting-xdebug-working
xdebug.remote_connect_back=0
xdebug.remote_host=docker.for.mac.localhost
## End For MAC/Docker
And I added into docker-compose.yml

services:
  php:
    ......
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    ......    

And then I configured PHPStorm using
Debug port = 9000
And i mapped the host path to the docker path

We can remove the remote logs for performance if needed

**Comment by Larzack** [comment]
@hschaeidt thanks for the doc. 
You can leave port 9000 because the IP are diffrent. php-fpm is inside the Docker container while the Xdebug port is your computer host. 
Also port 9000 is never opened outside de Docker container. 
And even if both 9000 ports are opened, it will be easilly to change "9000:9000" to "XXXX:9000" to the docker-compose file than changing préférences into PHPStorm.

**Comment by hschaeidt** [comment]
You're right, there is no real port conflict as long as port 9000 is not mapped. Thanks for pointing that out.

The config in the related PR #560 has been tested on mac, using docker for mac version 18.06-ce. Could you please test the settings and give a quick feedback if everything works as expected?

Regarding the `docker.for.mac.localhost`, it has been deprecated in 18.03 in favor of `host.docker.internal`.

Source:
- https://forums.docker.com/t/understanding-the-docker-for-mac-localhost-behavior/41921/5
- https://docs.docker.com/docker-for-mac/networking/#per-container-ip-addressing-is-not-possible

**Comment by Larzack** [comment]
@hschaeidt tested and works.
The documentation to configure PHPStorm should be inside this doc (few lines)

Regards
