### ISSUE TITLE
Pictures from distribution didn't work

### ISSUE THREAD

**Issue by xElysioN** [api-platform/docs#578]
Hi, 
Pictures from the documentation make 404 but showing great in github : 

https://api-platform.com/docs/core => https://api-platform.com/docs/distribution/images/swagger-ui-1.png ( https://github.com/api-platform/docs/blob/2.3/core/index.md)

https://api-platform.com/docs/distribution => https://api-platform.com/docs/distribution/images/api-platform-2.2-pwa-react.png

I've tested with Firefox 61.0.2 & Chrome 68.0.3.

**Comment by borNfreee** [comment]
duplicate https://github.com/api-platform/website/issues/50

It was fixed but reverted https://github.com/api-platform/docs/pull/565 so the issue still exists
