### ISSUE TITLE
Add documentation about multiple values of the search filter

### ISSUE THREAD

**Issue by alanpoulain** [api-platform/docs#601]
Searching multiple values for the same property is not documented.
Example:
`/books?author[]=/authors/1&author[]=/authors/2`

See: https://github.com/api-platform/core/issues/1985

**Comment by teohhanhui** [comment]
Definitely my fault. :see_no_evil:

**Comment by lcottingham** [comment]
How does this work on graphql when the schema enforces a `property: String` during introspection? How would I input multiple search values for the same property?

`
query getObjects ($values: String) {
        objects (foo: $values) {
            edges { ...
`
