### ISSUE TITLE
Blank doc pages

### ISSUE THREAD

**Issue by simshaun** [api-platform/docs#651]
I Googled "api platform pre_read" and clicked the result that leads to https://api-platform.com/docs/core/events/

I get a blank page:
![image](https://user-images.githubusercontent.com/379519/48390453-1f72bf80-e6d0-11e8-843f-e88cb8aaa94e.png)

I tried a little debugging but couldn't figure out what's going on other than whatever is problematic appears to be cached. If I clear browser cache & offline storage data then refresh, the page loads.

**Comment by antograssiot** [comment]
> If you encounter issues with our website, you need to flush the cache of your browser (Ctrl+R is not enough). It's because we disabled a @gatsbyjs plugin (gatsby-plugin-offline) that was causing issues, and this plugin was registering a service worker.
Sorry for the inconvenience
https://twitter.com/ApiPlatform/status/1061903324734279680

Unregistering the service worker is what actually solves the problem, sorry again. May we close ?

**Comment by simshaun** [comment]
Ah. Thanks

**Comment by dunglas** [comment]
https://github.com/api-platform/website/commit/5fce8f31727fbdf9d028c009a80223b23e6acfae should fix the problem, even without clearing the cache.
