### ISSUE TITLE
Obsolete URL for create-react-app documentation about environment variables

### ISSUE THREAD

**Issue by CHiPs44** [api-platform/docs#655]
On the https://api-platform.com/docs/admin/getting-started#installation-1 page, you reference the https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables URL.

The create-react-app documentation for this is now at https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables.

**Comment by dunglas** [comment]
Thanks for reporting! Fixed in ebcec31c925850011f32dcd04e599b6a7eafca5a.
