### ISSUE TITLE
Upgrade path from 1.x to 2.x

### ISSUE THREAD

**Issue by soyuka** [api-platform/docs#67]
Should we add something like this to the docs or you think it's not necessary?

**Comment by dunglas** [comment]
It would be very helpful to have such documentation!

**Comment by soyuka** [comment]
We didn't had Annotations in 1.x right? I can make a draft regarding yaml configurations (filters + operations).

**Comment by Simperfit** [comment]
I think this is needed

**Comment by Simperfit** [comment]
#141 is going to fix this but it needs more work
