### ISSUE TITLE
No versioning for documentation

### ISSUE THREAD

**Issue by raresserban** [api-platform/docs#745]
Hello,
Currently I do not see any versioning for the documentation. It seems like the docs page is always up to date with the latest changes here, but this is misleading because people running the latest version at the time of writing, 2.3, don't know what features are available.

For example, I wanted to use the Symfony Messenger integration described here https://api-platform.com/docs/core/messenger/, but it is only available in version 2.4. I see that version 2.4 is in beta so I used that version, but still, that version does not contain the `output=false` option on the `ApiResource` annotation presented in the current version of the docs...

As you can see everything gets too confusing, I think there should be versioning like in Symfony, the latest version (2.3 right now) to be selected by default but also have the option to select the other versions.

Thank you.

**Comment by WebCu** [comment]
Yes, this is very confusing. @dunglas Do you have plans to add this in the near future? Symfony does it and its really much more easy. 

Thanks in advance!

**Comment by dunglas** [comment]
Actually, the documentation is versioned, and all version are available in this GitHub repo. On the website, the docs of latest release **or** pre-release (aka beta) is published. So currently, it's 2.4 (and not master). It's done on purpose as an incentive to test the beta versions. I understand that it can look though, but it works pretty well.

Still, there is an issue to fix, the link on the Download button on the homepage point to 2.3. It should reference 2.4. I'll fix this as soon as possible.

**Comment by dunglas** [comment]
Link fixed: https://github.com/api-platform/website/commit/2366d354ef9cf97d2ba4c5ffe6b7dd275234539b

**Comment by WebCu** [comment]
Thanks for the response @dunglas! Some thoughts about it:

> Actually, the documentation is versioned, and all version are available in this GitHub repo. 

I used the website like my primary source of information because is easier find the info there than here.

>On the website, the docs of latest release **or** pre-release (aka beta) is published. 

Good to know! I believe is worthy mention this some where in the website because some newbies to API Platform like myself :) could get easily confuse.

>It's done on purpose as an incentive to test the beta versions. I understand that it can look though, but it works pretty well.

I understand your point of view. From the point of view of a developer that needs maintain a system is a little bit more complicated. Being aware that is made intentionally have clarified the things a lot for me. 

I have been using API platform for around 3 months and I'm enjoying it. Keep the good work. Thanks!

**Comment by dunglas** [comment]
Thank you for the feedback! Maybe could we:

* Add a version selector on the website (would require some changes to the Gatsby app)
* Add a warning or a notice somewhere when browsing the docs for an old, or a beta version

**Comment by WebCu** [comment]
That would be great! I discovered Gatsby recently. I would like to help in the implementation of these changes.

**Comment by raresserban** [comment]
I see that versioning is now available, so I am closing this issue.
Eg:
https://api-platform.com/docs/v2.3/core/dto/
https://api-platform.com/docs/master/core/dto/
