### ISSUE TITLE
File upload documentation 

### ISSUE THREAD

**Issue by AlexandreHagen** [api-platform/docs#78]
A documentation about upload files system is existing or is planned ? 
Like describe in https://github.com/api-platform/api-platform/issues/12

**Comment by Simperfit** [comment]
We will be glad to read that PR if you have some time to write it :)

**Comment by AlexandreHagen** [comment]
With pleasure. However, upload files (base 64) do not work to me. I am sure is because I don't understand something. But without documentation how to know ? 
Can you please provide, at least, annotation and property used in entities to upload files with ```DataUriNormalizer```?
I am using VichUploaderBundle and impossible to get an instance of ```UploadedFile ``` or ```File```class.

**Comment by benjaminrau** [comment]
Hi guys.

I am not sure if uploads should be part of Api Platform - i cant argue but to me it seems to be smth different.

Maybe we should just have some example how it can be done to be compatible ApiPlatform resource.

I implemented file upload with MediaBundle support recently - maybe you can have a look on the Gist if put together and tell me your opinion if its worth to be documented.

https://gist.github.com/benjaminrau/7010ad3becd6a5d86339d1926b518e61

I could take over documenting my approach.

Cheers Ben

**Comment by teohhanhui** [comment]
Related: api-platform/api-platform#12

**Comment by teohhanhui** [comment]
I'd like to see documentation on integration with `VichUploaderBundle` (because it's a popular one and quite simple), but of course PRs are welcome for integration with other media upload bundles like `SonataMediaBundle` too.

**Comment by teohhanhui** [comment]
@AlexandreHagen Do you think you can help with documenting the `VichUploaderBundle` integration? (If you got it working in a nice way.)

I have my own way of doing it too, which I suppose I can share when I find the time.

**Comment by dunglas** [comment]
Having a doc for the SonataMedia integration would be very interesting too. Of course having a doc for both VichUploaderBundle and SonataMedia is the best.

**Comment by benjaminrau** [comment]
Hi guys.

So far i created a bundle both as an example but also to use. Ive created it while i was creating a solution for a project, so i had to remove the business logic. I think its pretty clean now.

I started with an documentation also: https://github.com/benjaminrau/media-api

Anyway i wouldnt call myself an experienced Symfony developer, so be indulge with me ;)

Looking foward to get some feedback.

Cheers Ben

**Comment by pierre-H** [comment]
Any news ?

**Comment by benjaminrau** [comment]
@pierre-H you have some feedback? still waiting ;)

**Comment by pierre-H** [comment]
@benjaminrau I still didn't try because I had to work on another project at the same time.

So no feedback for the moment 😢

**Comment by Nightbr** [comment]
@benjaminrau Hey, I have implemented a similar MediaBundle than yours. I modify several things such as the PostLoadEventListener.php in order to take into account the Media context:
```

<?php
namespace MediaBundle\EventListener;

use Doctrine\ORM\Event\LifecycleEventArgs;
use MediaBundle\Entity\Media;
use Sonata\MediaBundle\Provider\MediaProviderInterface;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\HttpFoundation\RequestStack;

class PostLoadEventListener
{
    /**
     * @var Container
     */
    private $container;

    /**
     * @var RequestStack
     */
    private $requestStack;

    public function __construct(Container $container, RequestStack $requestStack)
    {
        $this->container = $container;
        $this->requestStack = $requestStack;
    }

    public function postLoad(LifecycleEventArgs $args)
    {
        $class = $this->container->getParameter('sonata.media.media.class');
        $entity = $args->getEntity();
        if ($entity instanceof $class && $entity->getProviderName()) {
            /** @var MediaProviderInterface $provider */
            $entityContext = $entity->getContext();
            $provider = $this->container->get($entity->getProviderName());
            // Add format from context
            foreach ($provider->getFormats() as $key => $defintion) {
                if ($key == 'admin') {
                    break;
                }
                list($context, $formatName) = explode('_', $key);
                if ($context == $entityContext) {
                    $this->addFormat($context, $formatName, $provider, $entity);
                }
            }
            // Add reference
            $this->addFormat('reference', null, $provider, $entity);
        }
    }

    /**
     * Add format to Media Entity (serialization output)
     * @param string $context
     * @param ?string $formatName
     * @param MediaProviderInterface $provider
     * @param Media $entity
     */
    private function addFormat($context, $formatName = null, $provider, $entity)
    {
        $key = $context;
        if (!is_null($formatName)) {
            $key = $context.'_'.$formatName;
        }
        $format = $provider->getHelperProperties($entity, $key);
        if (isset($format['src']) && strpos($format['src'], '/') === 0 && $this->requestStack->getCurrentRequest()) {
            $format['src'] = $this->requestStack->getCurrentRequest()->getSchemeAndHttpHost() . $format['src'];
        }
        $format['context'] = $context;
        $format['format'] = $formatName;
        unset($format['srcset']);
        unset($format['sizes']);
        $entity->addFormat($format);
    }
}
```

If you want to talk about this and share code, feel free to contact me ;) Perhaps we can create and publish an OpenSource Bundle together if you want!

**Comment by Nightbr** [comment]
Hey, here is my implementation based on @benjaminrau work!

https://github.com/MoltenCoreIO/api-media

I add some fixtures such as remove tmp image after upload is completed, manage media context, ...

Feel free to create issue for feedback! Thanks

**Comment by alanpoulain** [comment]
Fixed: https://github.com/api-platform/docs/commit/4fdaad1153550daa7ae3c85cbeee60512c4253f7#diff-128ef58379fc048ad82e70b3fb3bc364
