### ISSUE TITLE
Wrong description of DeserializeListener?

### ISSUE THREAD

**Issue by antode** [api-platform/docs#895]
[events.md#L29](https://github.com/api-platform/docs/blame/master/core/events.md#L29)

> Deserializes data into a PHP entity (GET, POST, DELETE); updates the entity retrieved using the data provider (PUT)

`GET` method is listed, but there is `isMethodSafe` check in [DeserializeListener.php#L76](https://github.com/api-platform/core/blob/master/src/EventListener/DeserializeListener.php#L76)
```php
if (
    ...
    || $request->isMethodSafe(false)
    ...
) {
    return;
}
```

**Comment by soyuka** [comment]
definitely

**Comment by alanpoulain** [comment]
Fixed in https://github.com/api-platform/docs/commit/0f42f223ba2da278ee86e4d48783ed77a27c93a0.
