### ISSUE TITLE
Document the ContextAwareDataPersisterInterface interface

### ISSUE THREAD

**Issue by dunglas** [api-platform/docs#902]
https://github.com/api-platform/core/blob/master/src/DataPersister/ContextAwareDataPersisterInterface.php should be used in https://github.com/api-platform/docs/blob/2.5/core/data-persisters.md

**Comment by lukasluecke** [comment]
Should the current documentation be replaced, and always use the `ContextAwareDataPersisterInterface`, or should both be documented with a quick note on when to use which one?

**Comment by dunglas** [comment]
I suggest to replace the existing interface, and to add a comment telling that `DataPersisterInterface` should be used if the context isn't necessary.
