### ISSUE TITLE
Document plain identifiers and relation updates

### ISSUE THREAD

**Issue by soyuka** [api-platform/docs#909]
See https://github.com/api-platform/core/pull/3145 we should document this use case.

**Comment by harshraj22** [comment]
Hi. Can you please explain little more as what changes you wish ?
Do you want a [issue template](https://help.github.com/en/articles/manually-creating-a-single-issue-template-for-your-repository) created for this repo similar to used in #3145 ?

**Comment by soyuka** [comment]
Hi @harshraj22 this is about documenting the use case behind the investigation of  api-platform/core#3133 which lead to api-platform/core#3145 see https://github.com/api-platform/core/pull/3145/files#diff-bbc4a791c60880831ee82ed7288684beR187
