### ISSUE TITLE
Documentation for Vuejs code generation

### ISSUE THREAD

**Issue by jraller** [api-platform/docs#938]
The page https://api-platform.com/docs/client-generator/vuejs/ in the section that provided the command for generating the code leaves out the `--generator vue` portion of the command.

Should

```
$ npx @api-platform/client-generator https://demo.api-platform.com src/ --resource book
```

be

```
$ npx @api-platform/client-generator --generator vue https://demo.api-platform.com src/ --resource book
```

because the code generated without that appears to be react code.

**Comment by dunglas** [comment]
Thanks for reporting @jraller! Fixed in 7fbc09f079f2f485c1383d123a16c235ca3cdab2.
